### ISSUE TITLE
Missing Node import for Webpack

### ISSUE THREAD

**Issue by travis-r6s** [eidellev/adonis-stardust#12]
When using this package with Webpack + your other Adonis Inertia package in SSR mode, Webpack fails to import `initRoutes`. I believe it is because the `main` export field in `package.json` is set to the provider file (`build/providers/StardustProvider.js`), as opposed to the client build `build/client/index.js`, so Webpack is trying to import `initRoutes` and `stardust` from `StardustProvider.js`.

If this is just a case of updating the package `exports` fields, and updating the provider path, I am happy to create a PR for this.

**Comment by eidellev** [comment]
Hi @thetre97 
Thanks for reporting this! In theory this is covered by the `browser` field, but there may be some cases where this doesn't work.
Can you share your node version and if you're using encore or some other asset manager/bundler?

**Comment by eidellev** [comment]
this has been fixed in `v3.0.0`
please note the breaking changes

**Comment by jordin-marshall** [comment]
This is currently still an issue for me using inertia + vue 3
`Uncaught TypeError: (0 , _eidellev_adonis_stardust__WEBPACK_IMPORTED_MODULE_6__.initRoutes) is not a function`
